### ISSUE TITLE
Direct to blob storage rather than file share

### ISSUE THREAD

**Issue by sarahbenjamin** [bhummerstone/azure-templates#1]
It works great!
Any idea how to change it to use Blob storage rather than file share?
I want to be able to direct 3 users to one storage account but three separate folders inside a blob container.
Is that doable and how?

**Comment by bhummerstone** [comment]
Sorry, I completely missed this one!

This is now available natively in Blob: https://docs.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support-how-to
