### ISSUE TITLE
sftp-custom-image.json template not pulling the ACI hosted image

### ISSUE THREAD

**Issue by sthakkar17** [bhummerstone/azure-templates#6]
I have done all 5 steps from 6 steps to handle the static ssh key. 

In step 6, I have used your ARM template sftp-custom-image.json it seems not to pull the image and terminate it. 

![image](https://user-images.githubusercontent.com/55979309/148909144-c7b79f47-9220-4d51-bdb4-2aaa7d4eee97.png)

**Comment by bhummerstone** [comment]
Could you check out the steps here to see what the detailed events are?
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#unable-to-pull-image

**Comment by sthakkar17** [comment]
Thank you, @bhummerstone , for the help. 
However, I am not actively working on this as of now. I will take a look into this once I got some time. 
If you want, you can close this issue. 

We shifted to focus on the VM approach as this container approach is being expensive as we grow more user login and 24 hours availability of the server. 

I have used OpenSSH on our windows server and configure SSH and SFTP on it.
